# objects are assumed to be 1x1 squares or 1/9th of a tile space
# objects lists of 2 itesms: model name and hp of object
# future work may include other sizes

#helper strings for the arrays
var char_path="theme_museum/ghostbusters/001_characters/"
var outside_object_path=""
var hp=1000

var inside_objects=gen_inside_obj()
#[[char_path+"vigo/vigo",hp],[char_path+"boogieman/boogieman",hp]]
var outside_objects=inside_objects

func gen_inside_obj():
	var tmp=[]
	tmp.append([char_path+"vigo/vigo",hp])
	tmp.append([char_path+"boogieman/boogieman",hp])
	tmp.append([char_path+"abaia/abaia",hp])
	tmp.append([char_path+"achiraminion/achiraminion",hp])
	tmp.append([char_path+"animatedtoaster/animatedtoaster",hp])
	tmp.append([char_path+"azeltor/azeltor",hp])
	tmp.append([char_path+"ballroomghosttango/ballroomghosttango",hp])
	tmp.append([char_path+"behemoth/behemoth",hp])
	tmp.append([char_path+"bellhopghost/bellhopghost",hp])
	tmp.append([char_path+"bloodymary/bloodymary",hp])
	tmp.append([char_path+"bluelou/bluelou",hp])
	tmp.append([char_path+"boghound/boghound",hp])
	tmp.append([char_path+"boogaloo/boogaloo",hp])
	tmp.append([char_path+"busdriver/busdriver",hp])
	tmp.append([char_path+"catsith/catsith",hp])
	tmp.append([char_path+"chairmanminion/chairmanminion",hp])
	tmp.append([char_path+"chefghost/chefghost",hp])
	tmp.append([char_path+"cheonyeogwisin/cheonyeogwisin",hp])
	tmp.append([char_path+"christmasfuture/christmasfuture",hp])
	tmp.append([char_path+"christmaspast/christmaspast",hp])
	tmp.append([char_path+"chupacabra/chupacabra",hp])
	tmp.append([char_path+"clamper/clamper",hp])
	tmp.append([char_path+"cuca/cuca",hp])
	tmp.append([char_path+"death/death",hp])
	tmp.append([char_path+"dixie/dixie",hp])
	tmp.append([char_path+"doctormacather/doctormacather",hp])
	tmp.append([char_path+"dreamgirl/dreamgirl",hp])
	tmp.append([char_path+"dueogsini/dueogsini",hp])
	tmp.append([char_path+"ectoclone/ectoclone",hp])
	tmp.append([char_path+"eggghost/eggghost",hp])
	tmp.append([char_path+"ellengold/ellengold",hp])
	tmp.append([char_path+"enraenra/enraenra",hp])
	tmp.append([char_path+"ethankaine/ethankaine",hp])
	tmp.append([char_path+"feifei/feifei",hp])
	tmp.append([char_path+"female_ghostbuster/female_ghostbuster_2_face_1",hp])
	tmp.append([char_path+"female_ghostbuster/female_ghostbuster_2_face_2",hp])
	tmp.append([char_path+"flatwoods/flatwoods",hp])
	tmp.append([char_path+"geniedark/geniedark",hp])
	tmp.append([char_path+"genieearth/genieearth",hp])
	tmp.append([char_path+"geniefire/geniefire",hp])
	tmp.append([char_path+"genielight/genielight",hp])
	tmp.append([char_path+"geniewater/geniewater",hp])
	tmp.append([char_path+"gertrudealdridge/gertrudealdridge",hp])
	tmp.append([char_path+"ghash/ghash",hp])
	tmp.append([char_path+"ghostballoon/ghostballoon_1",hp])
	tmp.append([char_path+"ghostballoon/ghostballoon_2",hp])
	tmp.append([char_path+"ghostballoon/ghostballoon_3",hp])
	tmp.append([char_path+"ghostbride/ghostbride_1",hp])
	tmp.append([char_path+"ghostbufflo/ghostbufflo",hp])
	tmp.append([char_path+"goast/goast",hp])
	tmp.append([char_path+"golemdark/golemdark",hp])
	tmp.append([char_path+"golemearth/golemearth",hp])
	tmp.append([char_path+"golemfire/golemfire",hp])
	tmp.append([char_path+"golemlight/golemlight",hp])
	tmp.append([char_path+"gozer/gozer",hp])
	tmp.append([char_path+"gremlin/gremlin",hp])
	tmp.append([char_path+"grootslang/grootslang",hp])
	tmp.append([char_path+"grundel/grundel",hp])
	tmp.append([char_path+"hungrymanitou/hungrymanitou",hp])
	tmp.append([char_path+"iconghost/iconghost",hp])
	tmp.append([char_path+"idulnas/idulnas",hp])
	tmp.append([char_path+"ivoshandor/ivoshandor",hp])
	tmp.append([char_path+"jeosungsaja/jeosungsaja",hp])
	tmp.append([char_path+"jiangshi/jiangshi",hp])
	tmp.append([char_path+"kappa/kappa",hp])
	tmp.append([char_path+"kasaobake/kasaobake",hp])
	tmp.append([char_path+"kozaraiminion/kozaraiminion",hp])
	tmp.append([char_path+"ladyslimer/ladyslimer",hp])
	tmp.append([char_path+"leprechaun/leprechaun",hp])
	tmp.append([char_path+"libraryghost/libraryghost",hp])
	tmp.append([char_path+"libraryghost/libraryghostscary",hp])
	tmp.append([char_path+"libraryghost_playmobile/libraryghost_playmobile",hp])
	tmp.append([char_path+"livingarmordark/livingarmordark",hp])
	tmp.append([char_path+"livingarmorearth/livingarmorearth",hp])
	tmp.append([char_path+"livingarmorfire/livingarmorfire",hp])
	tmp.append([char_path+"livingarmorlight/livingarmorlight",hp])
	tmp.append([char_path+"livingarmorwater/livingarmorwater",hp])
	tmp.append([char_path+"lizard/lizard",hp])
	tmp.append([char_path+"lotan/lotan",hp])
	tmp.append([char_path+"male_ghostbuster/male_ghostbuster_1_face_1",hp])
	tmp.append([char_path+"male_ghostbuster/male_ghostbuster_1_face_2",hp])
	tmp.append([char_path+"male_ghostbuster/male_ghostbuster_3_face_1",hp])
	tmp.append([char_path+"male_ghostbuster/male_ghostbuster_3_face_2",hp])
	tmp.append([char_path+"mandragora/mandragora",hp])
	tmp.append([char_path+"maneatingtree/maneatingtree",hp])
	tmp.append([char_path+"mayhem/mayhem",hp])
	tmp.append([char_path+"mayhemminion/mayhemminion",hp])
	tmp.append([char_path+"menreiki/menreiki",hp])
	tmp.append([char_path+"mimicdark/mimicdark",hp])
	tmp.append([char_path+"mimicearth/mimicearth",hp])
	tmp.append([char_path+"mimicfire/mimicfire",hp])
	tmp.append([char_path+"mimiclight/mimiclight",hp])
	tmp.append([char_path+"mimicwater/mimicwater",hp])
	tmp.append([char_path+"nekomata/nekomata",hp])
	tmp.append([char_path+"ninetailfox/ninetailfox",hp])
	tmp.append([char_path+"nunzioscoleri/nunzioscoleri",hp])
	tmp.append([char_path+"phoenix/phoenix",hp])
	tmp.append([char_path+"playmobile_man/playmobile_man",hp])
	tmp.append([char_path+"playmobile_woman/playmobile_woman",hp])
	tmp.append([char_path+"poltergeist/poltergeist",hp])
	tmp.append([char_path+"purpleghost/purpleghost",hp])
	tmp.append([char_path+"quetzalcohuatl/quetzalcohuatl",hp])
	tmp.append([char_path+"ravana/ravana",hp])
	tmp.append([char_path+"ringreaderghost/ringreaderghost",hp])
	tmp.append([char_path+"ringreaderghostminion/ringreaderghostminion",hp])
	tmp.append([char_path+"sandman/sandman",hp])
	tmp.append([char_path+"sanhain/sanhain",hp])
	tmp.append([char_path+"sixtailfox/sixtailfox",hp])
	tmp.append([char_path+"slimer/slimer",hp])
	tmp.append([char_path+"specters/specters",hp])
	tmp.append([char_path+"spiderwitch/spiderwitch",hp])
	tmp.append([char_path+"spiderwitchminion/spiderwitchminion",hp])
	tmp.append([char_path+"staypuft/staypuft",hp])
	tmp.append([char_path+"stingyjack/stingyjack",hp])
	tmp.append([char_path+"subwayrat/subwayrat",hp])
	tmp.append([char_path+"tempus/tempus",hp])
	tmp.append([char_path+"tengu/tengu",hp])
	tmp.append([char_path+"theatreghost/theatreghost",hp])
	tmp.append([char_path+"threetailfox/threetailfox",hp])
	tmp.append([char_path+"tonyscoleri/tonyscoleri",hp])
	tmp.append([char_path+"vigominion/vigominion",hp])
	tmp.append([char_path+"vinz/vinz",hp])
	tmp.append([char_path+"washingtonsquareghost/washingtonsquareghost",hp])
	tmp.append([char_path+"wispdark/wispdark",hp])
	tmp.append([char_path+"wispearth/wispearth",hp])
	tmp.append([char_path+"wispfire/wispfire",hp])
	tmp.append([char_path+"wisplight/wisplight",hp])
	tmp.append([char_path+"wispwater/wispwater",hp])
	tmp.append([char_path+"xiezhidark/xiezhidark",hp])
	tmp.append([char_path+"xiezhiearth/xiezhiearth",hp])
	tmp.append([char_path+"xiezhifire/xiezhifire",hp])
	tmp.append([char_path+"xiezhilight/xiezhilight",hp])
	tmp.append([char_path+"xiezhiwater/xiezhiwater",hp])
	tmp.append([char_path+"zombietaxidriver/zombietaxidriver",hp])
	tmp.append([char_path+"zuul/zuul",hp])
	return tmp


# saturation is the number of objects to place in a single tile, 1,2, or 3
var saturation=3
# level object count is the number of roms and columns that will have objects 
# on them - 1 to 60, should be based on object count, and how many repeats 
# there should be.
var level_object_count=30
